include ../Makefile.in

all: lib

lib: libstdio.so

clearerr.o  :clearerr.c
	$(CC) -fPIC -g -c -Wall $^ $(LDFLAGS)
fclose.o    :fclose.c
	$(CC) -fPIC -g -c -Wall $^ $(LDFLAGS)
feof.o      :feof.c
	$(CC) -fPIC -g -c -Wall $^ $(LDFLAGS)
ferror.o    :ferror.c
	$(CC) -fPIC -g -c -Wall $^ $(LDFLAGS)
fflush.o    :fflush.c
	$(CC) -fPIC -g -c -Wall $^ $(LDFLAGS)
fgetc.o     :fgetc.c
	$(CC) -fPIC -g -c -Wall $^ $(LDFLAGS)
fgetpos.o   :fgetpos.c
	$(CC) -fPIC -g -c -Wall $^ $(LDFLAGS)
fgets.o     :fgets.c
	$(CC) -fPIC -g -c -Wall $^ $(LDFLAGS)
fopen.o     :fopen.c
	$(CC) -fPIC -g -c -Wall $^ $(LDFLAGS)
fprintf.o   :fprintf.c
	$(CC) -fPIC -g -c -Wall $^ $(LDFLAGS)
fputc.o     :fputc.c
	$(CC) -fPIC -g -c -Wall $^ $(LDFLAGS)
fputs.o     :fputs.c
	$(CC) -fPIC -g -c -Wall $^ $(LDFLAGS)
fread.o     :fread.c
	$(CC) -fPIC -g -c -Wall $^ $(LDFLAGS)
freopen.o   :freopen.c
	$(CC) -fPIC -g -c -Wall $^ $(LDFLAGS)
fscanf.o    :fscanf.c
	$(CC) -fPIC -g -c -Wall $^ $(LDFLAGS)
fseek.o     :fseek.c
	$(CC) -fPIC -g -c -Wall $^ $(LDFLAGS)
fsetpos.o   :fsetpos.c
	$(CC) -fPIC -g -c -Wall $^ $(LDFLAGS)
ftell.o     :ftell.c
	$(CC) -fPIC -g -c -Wall $^ $(LDFLAGS)
fwrite.o    :fwrite.c
	$(CC) -fPIC -g -c -Wall $^ $(LDFLAGS)
getc.o      :getc.c
	$(CC) -fPIC -g -c -Wall $^ $(LDFLAGS)
getchar.o   :getchar.c
	$(CC) -fPIC -g -c -Wall $^ $(LDFLAGS)
gets.o      :gets.c
	$(CC) -fPIC -g -c -Wall $^ $(LDFLAGS)
perror.o    :perror.c
	$(CC) -fPIC -g -c -Wall $^ $(LDFLAGS)
printf.o    :printf.c
	$(CC) -fPIC -g -c -Wall $^ $(LDFLAGS)
putc.o      :putc.c
	$(CC) -fPIC -g -c -Wall $^ $(LDFLAGS)
putchar.o   :putchar.c
	$(CC) -fPIC -g -c -Wall $^ $(LDFLAGS)
puts.o      :puts.c
	$(CC) -fPIC -g -c -Wall $^ $(LDFLAGS)
remove.o    :remove.c
	$(CC) -fPIC -g -c -Wall $^ $(LDFLAGS)
rename.o    :rename.c
	$(CC) -fPIC -g -c -Wall $^ $(LDFLAGS)
rewind.o    :rewind.c
	$(CC) -fPIC -g -c -Wall $^ $(LDFLAGS)
scanf.o     :scanf.c
	$(CC) -fPIC -g -c -Wall $^ $(LDFLAGS)
setbuf.o    :setbuf.c
	$(CC) -fPIC -g -c -Wall $^ $(LDFLAGS)
setvbuf.o   :setvbuf.c
	$(CC) -fPIC -g -c -Wall $^ $(LDFLAGS)
sprintf.o   :sprintf.c
	$(CC) -fPIC -g -c -Wall $^ $(LDFLAGS)
sscanf.o    :sscanf.c
	$(CC) -fPIC -g -c -Wall $^ $(LDFLAGS)
tmpfile.o   :tmpfile.c
	$(CC) -fPIC -g -c -Wall $^ $(LDFLAGS)
tmpnam.o    :tmpnam.c
	$(CC) -fPIC -g -c -Wall $^ $(LDFLAGS)
ungetc.o    :ungetc.c
	$(CC) -fPIC -g -c -Wall $^ $(LDFLAGS)
vfprintf.o  :vfprintf.c
	$(CC) -fPIC -g -c -Wall $^ $(LDFLAGS)
vprintf.o   :vprintf.c
	$(CC) -fPIC -g -c -Wall $^ $(LDFLAGS)
vsprintf.o  :vsprintf.c
	$(CC) -fPIC -g -c -Wall $^ $(LDFLAGS)
xfgpos.o    :xfgpos.c
	$(CC) -fPIC -g -c -Wall $^ $(LDFLAGS)
xfiles.o    :xfiles.c
	$(CC) -fPIC -g -c -Wall $^ $(LDFLAGS)
xfopen.o    :xfopen.c
	$(CC) -fPIC -g -c -Wall $^ $(LDFLAGS)
xfoprep.o   :xfoprep.c
	$(CC) -fPIC -g -c -Wall $^ $(LDFLAGS)
xfrprep.o   :xfrprep.c
	$(CC) -fPIC -g -c -Wall $^ $(LDFLAGS)
xfspos.o    :xfspos.c
	$(CC) -fPIC -g -c -Wall $^ $(LDFLAGS)
xfwprep.o   :xfwprep.c
	$(CC) -fPIC -g -c -Wall $^ $(LDFLAGS)
xgenld.o    :xgenld.c
	$(CC) -fPIC -g -c -Wall $^ $(LDFLAGS)
xgetfld.o   :xgetfld.c
	$(CC) -fPIC -g -c -Wall $^ $(LDFLAGS)
xgetfloa.o  :xgetfloa.c
	$(CC) -fPIC -g -c -Wall $^ $(LDFLAGS)
xgetint.o   :xgetint.c
	$(CC) -fPIC -g -c -Wall $^ $(LDFLAGS)
xldtob.o    :xldtob.c
	$(CC) -fPIC -g -c -Wall $^ $(LDFLAGS)
xlitob.o    :xlitob.c
	$(CC) -fPIC -g -c -Wall $^ $(LDFLAGS)
xprintf.o   :xprintf.c
	$(CC) -fPIC -g -c -Wall $^ $(LDFLAGS)
xputfld.o   :xputfld.c
	$(CC) -fPIC -g -c -Wall $^ $(LDFLAGS)
xscanf.o    :xscanf.c
	$(CC) -fPIC -g -c -Wall $^ $(LDFLAGS)

libstdio.so :clearerr.o fclose.o feof.o ferror.o \
             fflush.o fgetc.o fgetpos.o fgets.o \
             fopen.o fprintf.o fputc.o fputs.o fread.o \
             freopen.o fscanf.o fseek.o fsetpos.o ftell.o \
             fwrite.o getchar.o getc.o gets.o perror.o \
             printf.o putchar.o putc.o puts.o remove.o \
             rename.o rewind.o scanf.o setbuf.o setvbuf.o \
             sprintf.o sscanf.o tmpfile.o tmpnam.o ungetc.o \
             vfprintf.o vprintf.o vsprintf.o xfgpos.o xfiles.o \
             xfopen.o xfoprep.o xfrprep.o xfspos.o xfwprep.o \
             xgenld.o xgetfld.o xgetfloa.o xgetint.o xldtob.o  \
             xlitob.o xprintf.o xputfld.o xscanf.o ../errno/errno.o
	$(CC) -shared -Wl,-soname,$@ -o $@  $^ $(CFLAGS) $(LDFLAGS)
	mv $@ ../lib/

.PHONY: clean
clean:
	- rm *.o *.so
