include ../Makefile.in

all: lib

lib: libstdio.so

clearerr.o  :clearerr.c
	$(CC) -fPIC -g -c -Wall $^ -I ../include
fclose.o    :fclose.c
	$(CC) -fPIC -g -c -Wall $^ -I ../include
feof.o      :feof.c
	$(CC) -fPIC -g -c -Wall $^ -I ../include
ferror.o    :ferror.c
	$(CC) -fPIC -g -c -Wall $^ -I ../include
fflush.o    :fflush.c
	$(CC) -fPIC -g -c -Wall $^ -I ../include
fgetc.o     :fgetc.c
	$(CC) -fPIC -g -c -Wall $^ -I ../include
fgetpos.o   :fgetpos.c
	$(CC) -fPIC -g -c -Wall $^ -I ../include
fgets.o     :fgets.c
	$(CC) -fPIC -g -c -Wall $^ -I ../include
fopen.o     :fopen.c
	$(CC) -fPIC -g -c -Wall $^ -I ../include
fprintf.o   :fprintf.c
	$(CC) -fPIC -g -c -Wall $^ -I ../include
fputc.o     :fputc.c
	$(CC) -fPIC -g -c -Wall $^ -I ../include
fputs.o     :fputs.c
	$(CC) -fPIC -g -c -Wall $^ -I ../include
fread.o     :fread.c
	$(CC) -fPIC -g -c -Wall $^ -I ../include
freopen.o   :freopen.c
	$(CC) -fPIC -g -c -Wall $^ -I ../include
fscanf.o    :fscanf.c
	$(CC) -fPIC -g -c -Wall $^ -I ../include
fseek.o     :fseek.c
	$(CC) -fPIC -g -c -Wall $^ -I ../include
fsetpos.o   :fsetpos.c
	$(CC) -fPIC -g -c -Wall $^ -I ../include
ftell.o     :ftell.c
	$(CC) -fPIC -g -c -Wall $^ -I ../include
fwrite.o    :fwrite.c
	$(CC) -fPIC -g -c -Wall $^ -I ../include
getc.o      :getc.c
	$(CC) -fPIC -g -c -Wall $^ -I ../include
getchar.o   :getchar.c
	$(CC) -fPIC -g -c -Wall $^ -I ../include
gets.o      :gets.c
	$(CC) -fPIC -g -c -Wall $^ -I ../include
perror.o    :perror.c
	$(CC) -fPIC -g -c -Wall $^ -I ../include
printf.o    :printf.c
	$(CC) -fPIC -g -c -Wall $^ -I ../include
putc.o      :putc.c
	$(CC) -fPIC -g -c -Wall $^ -I ../include
putchar.o   :putchar.c
	$(CC) -fPIC -g -c -Wall $^ -I ../include
puts.o      :puts.c
	$(CC) -fPIC -g -c -Wall $^ -I ../include
remove.o    :remove.c
	$(CC) -fPIC -g -c -Wall $^ -I ../include
rename.o    :rename.c
	$(CC) -fPIC -g -c -Wall $^ -I ../include
rewind.o    :rewind.c
	$(CC) -fPIC -g -c -Wall $^ -I ../include
scanf.o     :scanf.c
	$(CC) -fPIC -g -c -Wall $^ -I ../include
setbuf.o    :setbuf.c
	$(CC) -fPIC -g -c -Wall $^ -I ../include
setvbuf.o   :setvbuf.c
	$(CC) -fPIC -g -c -Wall $^ -I ../include
sprintf.o   :sprintf.c
	$(CC) -fPIC -g -c -Wall $^ -I ../include
sscanf.o    :sscanf.c
	$(CC) -fPIC -g -c -Wall $^ -I ../include
tmpfile.o   :tmpfile.c
	$(CC) -fPIC -g -c -Wall $^ -I ../include
tmpnam.o    :tmpnam.c
	$(CC) -fPIC -g -c -Wall $^ -I ../include
ungetc.o    :ungetc.c
	$(CC) -fPIC -g -c -Wall $^ -I ../include
vfprintf.o  :vfprintf.c
	$(CC) -fPIC -g -c -Wall $^ -I ../include
vprintf.o   :vprintf.c
	$(CC) -fPIC -g -c -Wall $^ -I ../include
vsprintf.o  :vsprintf.c
	$(CC) -fPIC -g -c -Wall $^ -I ../include
xfgpos.o    :xfgpos.c
	$(CC) -fPIC -g -c -Wall $^ -I ../include
xfiles.o    :xfiles.c
	$(CC) -fPIC -g -c -Wall $^ -I ../include
xfopen.o    :xfopen.c
	$(CC) -fPIC -g -c -Wall $^ -I ../include
xfoprep.o   :xfoprep.c
	$(CC) -fPIC -g -c -Wall $^ -I ../include
xfrprep.o   :xfrprep.c
	$(CC) -fPIC -g -c -Wall $^ -I ../include
xfspos.o    :xfspos.c
	$(CC) -fPIC -g -c -Wall $^ -I ../include
xfwprep.o   :xfwprep.c
	$(CC) -fPIC -g -c -Wall $^ -I ../include
xgenld.o    :xgenld.c
	$(CC) -fPIC -g -c -Wall $^ -I ../include
xgetfld.o   :xgetfld.c
	$(CC) -fPIC -g -c -Wall $^ -I ../include
xgetfloa.o  :xgetfloa.c
	$(CC) -fPIC -g -c -Wall $^ -I ../include
xgetint.o   :xgetint.c
	$(CC) -fPIC -g -c -Wall $^ -I ../include
xldtob.o    :xldtob.c
	$(CC) -fPIC -g -c -Wall $^ -I ../include
xlitob.o    :xlitob.c
	$(CC) -fPIC -g -c -Wall $^ -I ../include
xprintf.o   :xprintf.c
	$(CC) -fPIC -g -c -Wall $^ -I ../include
xputfld.o   :xputfld.c
	$(CC) -fPIC -g -c -Wall $^ -I ../include
xscanf.o    :xscanf.c
	$(CC) -fPIC -g -c -Wall $^ -I ../include

libstdio.so :clearerr.o fclose.o feof.o ferror.o \
             fflush.o fgetc.o fgetpos.o fgets.o \
             fopen.o fprintf.o fputc.o fputs.o fread.o \
             freopen.o fscanf.o fseek.o fsetpos.o ftell.o \
             fwrite.o getchar.o getc.o gets.o perror.o \
             printf.o putchar.o putc.o puts.o remove.o \
             rename.o rewind.o scanf.o setbuf.o setvbuf.o \
             sprintf.o sscanf.o tmpfile.o tmpnam.o ungetc.o \
             vfprintf.o vprintf.o vsprintf.o xfgpos.o xfiles.o \
             xfopen.o xfoprep.o xfrprep.o xfspos.o xfwprep.o \
             xgenld.o xgetfld.o xgetfloa.o xgetint.o xldtob.o  \
             xlitob.o xprintf.o xputfld.o xscanf.o ../errno/errno.o
	$(CC) -shared -Wl,-soname,$@ -o $@  $^ $(CFLAGS) -I ../include
	mv $@ ../lib/

.PHONY: clean
clean:
	- rm *.o *.so
