OBJS = tctype

all: $(OBJS)

tctype: tctype.c isalnum.c isalpha.c iscntrl.c isdigit.c isgraph.c islower.c isprint.c ispunct.c isspace.c isupper.c isxdigit.c tctype.c tolower.c toupper.c xctype.c xtolower.c xtoupper.c

.PHONY: clean
clean:
	rm $(OBJS)
